"""create core application tables

Revision ID: 7a6ff3390755
Revises: 001
Create Date: 2026-08-06 18:23:51.942180

"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

revision = "7a6ff3390755"
down_revision = "001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assessment_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("knowledge_point_id", sa.String(length=36), nullable=False),
        sa.Column("subject", sa.String(length=100), nullable=False),
        sa.Column("item_type", sa.String(length=50), nullable=False),
        sa.Column("difficulty", sa.Integer(), nullable=False),
        sa.Column("grade_level", sa.Integer(), nullable=False),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column("options", sa.JSON(), nullable=False),
        sa.Column("correct_answer", sa.Text(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("cognitive_level", sa.String(length=50), nullable=False),
        sa.Column("common_misconceptions", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_assessment_kp_difficulty",
        "assessment_items",
        ["knowledge_point_id", "difficulty"],
        unique=False,
    )
    op.create_index(
        "idx_assessment_subject_grade", "assessment_items", ["subject", "grade_level"], unique=False
    )
    op.create_index(
        op.f("ix_assessment_items_knowledge_point_id"),
        "assessment_items",
        ["knowledge_point_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assessment_items_subject"), "assessment_items", ["subject"], unique=False
    )
    op.create_table(
        "assessment_results",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("pseudonym_id", sa.String(length=32), nullable=False),
        sa.Column("assessment_type", sa.String(length=50), nullable=False),
        sa.Column("subject", sa.String(length=100), nullable=False),
        sa.Column("knowledge_point_ids", sa.JSON(), nullable=False),
        sa.Column("grade_level", sa.Integer(), nullable=False),
        sa.Column("total_items", sa.Integer(), nullable=False),
        sa.Column("correct_count", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("time_spent_seconds", sa.Integer(), nullable=False),
        sa.Column("mastery_estimates", sa.JSON(), nullable=False),
        sa.Column("detected_misconceptions", sa.JSON(), nullable=False),
        sa.Column("item_results", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_result_subject_completed",
        "assessment_results",
        ["subject", "completed_at"],
        unique=False,
    )
    op.create_index(
        "idx_result_user_type", "assessment_results", ["user_id", "assessment_type"], unique=False
    )
    op.create_index(
        op.f("ix_assessment_results_assessment_type"),
        "assessment_results",
        ["assessment_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assessment_results_pseudonym_id"),
        "assessment_results",
        ["pseudonym_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assessment_results_subject"), "assessment_results", ["subject"], unique=False
    )
    op.create_index(
        op.f("ix_assessment_results_user_id"), "assessment_results", ["user_id"], unique=False
    )
    op.create_table(
        "child_profiles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("child_pseudonym_id", sa.String(length=32), nullable=False),
        sa.Column("daily_time_limit", sa.Integer(), nullable=True),
        sa.Column("allowed_subjects", sa.JSON(), nullable=False),
        sa.Column("blocked_keywords", sa.JSON(), nullable=False),
        sa.Column("learning_goals", sa.JSON(), nullable=False),
        sa.Column("learning_summary", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_child_profiles_child_pseudonym_id"),
        "child_profiles",
        ["child_pseudonym_id"],
        unique=False,
    )
    op.create_table(
        "parent_child_relations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("parent_id", sa.String(length=36), nullable=False),
        sa.Column("child_id", sa.String(length=36), nullable=False),
        sa.Column("relation_type", sa.String(length=50), nullable=False),
        sa.Column("is_guardian_consent_given", sa.Boolean(), nullable=False),
        sa.Column("guardian_consent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("can_view_dialogs", sa.Boolean(), nullable=False),
        sa.Column("can_view_assessments", sa.Boolean(), nullable=False),
        sa.Column("can_manage_account", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("parent_id", "child_id", name="uq_parent_child"),
    )
    op.create_index(
        op.f("ix_parent_child_relations_child_id"),
        "parent_child_relations",
        ["child_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_parent_child_relations_parent_id"),
        "parent_child_relations",
        ["parent_id"],
        unique=False,
    )
    op.create_table(
        "user_profiles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("pseudonym_id", sa.String(length=32), nullable=False),
        sa.Column("favorite_subjects", sa.JSON(), nullable=False),
        sa.Column("total_sessions", sa.Integer(), nullable=False),
        sa.Column("total_learning_minutes", sa.Integer(), nullable=False),
        sa.Column("streak_days", sa.Integer(), nullable=False),
        sa.Column("skills_mastered", sa.Integer(), nullable=False),
        sa.Column("mastery_summary", sa.JSON(), nullable=False),
        sa.Column("metacognition", sa.JSON(), nullable=False),
        sa.Column("affective", sa.JSON(), nullable=False),
        sa.Column("grade_level", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_profiles_pseudonym_id"), "user_profiles", ["pseudonym_id"], unique=True
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.Enum("USER", name="userrole"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "PENDING_VERIFICATION", "SUSPENDED", "DELETED", name="userstatus"),
            nullable=False,
        ),
        sa.Column("phone_encrypted", sa.Text(), nullable=True),
        sa.Column("phone_hash", sa.String(length=64), nullable=True),
        sa.Column("email_encrypted", sa.Text(), nullable=True),
        sa.Column("password_hash", sa.String(length=256), nullable=True),
        sa.Column("wechat_openid_encrypted", sa.Text(), nullable=True),
        sa.Column("real_name_encrypted", sa.Text(), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("pseudonym_id", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_users_role_status", "users", ["role", "status"], unique=False)
    op.create_index(op.f("ix_users_phone_hash"), "users", ["phone_hash"], unique=True)
    op.create_index(op.f("ix_users_pseudonym_id"), "users", ["pseudonym_id"], unique=True)
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_index(op.f("ix_users_status"), "users", ["status"], unique=False)
    op.create_table(
        "dialog_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("pseudonym_id", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("subject", sa.String(length=100), nullable=False),
        sa.Column("topic", sa.String(length=200), nullable=True),
        sa.Column("knowledge_point_id", sa.String(length=36), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "ENDED", "ARCHIVED", "DELETED", name="sessionstatus"),
            nullable=False,
        ),
        sa.Column("current_hint_level", sa.Integer(), nullable=False),
        sa.Column("current_strategy", sa.String(length=100), nullable=True),
        sa.Column("hint_escalation_count", sa.Integer(), nullable=False),
        sa.Column("wrong_streak", sa.Integer(), nullable=False),
        sa.Column("mastery_estimate", sa.Float(), nullable=False),
        sa.Column("meta_cognitive_goal", sa.String(length=100), nullable=True),
        sa.Column("turn_count", sa.Integer(), nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=False),
        sa.Column("moderation_status", sa.String(length=50), nullable=False),
        sa.Column("model_provider", sa.String(length=50), nullable=False),
        sa.Column("model_name", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_dialog_pseudonym_created",
        "dialog_sessions",
        ["pseudonym_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_dialog_user_status", "dialog_sessions", ["user_id", "status"], unique=False
    )
    op.create_index(
        op.f("ix_dialog_sessions_created_at"), "dialog_sessions", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_dialog_sessions_pseudonym_id"), "dialog_sessions", ["pseudonym_id"], unique=False
    )
    op.create_index(op.f("ix_dialog_sessions_status"), "dialog_sessions", ["status"], unique=False)
    op.create_index(
        op.f("ix_dialog_sessions_user_id"), "dialog_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "user_documents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("pseudonym_id", sa.String(length=32), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("file_extension", sa.String(length=20), nullable=False),
        sa.Column("file_size_bytes", sa.Integer(), nullable=False),
        sa.Column("storage_path", sa.String(length=500), nullable=False),
        sa.Column("processing_status", sa.String(length=20), nullable=False),
        sa.Column("processing_error", sa.Text(), nullable=True),
        sa.Column("processing_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("processing_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("moderation_status", sa.String(length=20), nullable=False),
        sa.Column("moderation_score", sa.Float(), nullable=True),
        sa.Column("moderation_categories", sa.JSON(), nullable=False),
        sa.Column("moderation_details", sa.JSON(), nullable=False),
        sa.Column("subject", sa.String(length=50), nullable=True),
        sa.Column("knowledge_point_id", sa.String(length=36), nullable=True),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column("last_accessed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("access_count", sa.Integer(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pseudonym_id"],
            ["users.pseudonym_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_user_docs_pseudonym_status",
        "user_documents",
        ["pseudonym_id", "processing_status"],
        unique=False,
    )
    op.create_index("idx_user_docs_subject", "user_documents", ["subject"], unique=False)
    op.create_index(
        op.f("ix_user_documents_file_extension"), "user_documents", ["file_extension"], unique=False
    )
    op.create_index(
        op.f("ix_user_documents_moderation_status"),
        "user_documents",
        ["moderation_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_documents_processing_status"),
        "user_documents",
        ["processing_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_documents_pseudonym_id"), "user_documents", ["pseudonym_id"], unique=False
    )
    op.create_index(op.f("ix_user_documents_subject"), "user_documents", ["subject"], unique=False)
    op.create_table(
        "dialog_messages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column(
            "role", sa.Enum("USER", "ASSISTANT", "SYSTEM", name="messagerole"), nullable=False
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("turn_number", sa.Integer(), nullable=False),
        sa.Column("strategy", sa.String(length=100), nullable=True),
        sa.Column("hint_level", sa.Integer(), nullable=True),
        sa.Column("intent", sa.String(length=100), nullable=True),
        sa.Column("moderation_result", sa.JSON(), nullable=False),
        sa.Column("moderation_degrade_level", sa.String(length=10), nullable=True),
        sa.Column("is_ai_generated", sa.Boolean(), nullable=False),
        sa.Column("watermark_info", sa.JSON(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column("ttft_ms", sa.Integer(), nullable=True),
        sa.Column("generation_ms", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["dialog_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_message_session_turn", "dialog_messages", ["session_id", "turn_number"], unique=False
    )
    op.create_index(
        "idx_message_user_created", "dialog_messages", ["user_id", "created_at"], unique=False
    )
    op.create_index(
        op.f("ix_dialog_messages_created_at"), "dialog_messages", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_dialog_messages_role"), "dialog_messages", ["role"], unique=False)
    op.create_index(
        op.f("ix_dialog_messages_session_id"), "dialog_messages", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_dialog_messages_user_id"), "dialog_messages", ["user_id"], unique=False
    )
    op.create_table(
        "document_chunks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("chunk_metadata", sa.JSON(), nullable=False),
        sa.Column("embedding_model", sa.String(length=100), nullable=False),
        sa.Column("embedding_dimension", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["user_documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_chunks_doc_index", "document_chunks", ["document_id", "chunk_index"], unique=False
    )
    op.create_index(
        op.f("ix_document_chunks_document_id"), "document_chunks", ["document_id"], unique=False
    )
    op.drop_index(op.f("ix_knowledge_points_parent_id"), table_name="knowledge_points")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_knowledge_points_parent_id"), "knowledge_points", ["parent_id"], unique=False
    )
    op.drop_index(op.f("ix_document_chunks_document_id"), table_name="document_chunks")
    op.drop_index("idx_chunks_doc_index", table_name="document_chunks")
    op.drop_table("document_chunks")
    op.drop_index(op.f("ix_dialog_messages_user_id"), table_name="dialog_messages")
    op.drop_index(op.f("ix_dialog_messages_session_id"), table_name="dialog_messages")
    op.drop_index(op.f("ix_dialog_messages_role"), table_name="dialog_messages")
    op.drop_index(op.f("ix_dialog_messages_created_at"), table_name="dialog_messages")
    op.drop_index("idx_message_user_created", table_name="dialog_messages")
    op.drop_index("idx_message_session_turn", table_name="dialog_messages")
    op.drop_table("dialog_messages")
    op.drop_index(op.f("ix_user_documents_subject"), table_name="user_documents")
    op.drop_index(op.f("ix_user_documents_pseudonym_id"), table_name="user_documents")
    op.drop_index(op.f("ix_user_documents_processing_status"), table_name="user_documents")
    op.drop_index(op.f("ix_user_documents_moderation_status"), table_name="user_documents")
    op.drop_index(op.f("ix_user_documents_file_extension"), table_name="user_documents")
    op.drop_index("idx_user_docs_subject", table_name="user_documents")
    op.drop_index("idx_user_docs_pseudonym_status", table_name="user_documents")
    op.drop_table("user_documents")
    op.drop_index(op.f("ix_dialog_sessions_user_id"), table_name="dialog_sessions")
    op.drop_index(op.f("ix_dialog_sessions_status"), table_name="dialog_sessions")
    op.drop_index(op.f("ix_dialog_sessions_pseudonym_id"), table_name="dialog_sessions")
    op.drop_index(op.f("ix_dialog_sessions_created_at"), table_name="dialog_sessions")
    op.drop_index("idx_dialog_user_status", table_name="dialog_sessions")
    op.drop_index("idx_dialog_pseudonym_created", table_name="dialog_sessions")
    op.drop_table("dialog_sessions")
    op.drop_index(op.f("ix_users_status"), table_name="users")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_pseudonym_id"), table_name="users")
    op.drop_index(op.f("ix_users_phone_hash"), table_name="users")
    op.drop_index("idx_users_role_status", table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_user_profiles_pseudonym_id"), table_name="user_profiles")
    op.drop_table("user_profiles")
    op.drop_index(op.f("ix_parent_child_relations_parent_id"), table_name="parent_child_relations")
    op.drop_index(op.f("ix_parent_child_relations_child_id"), table_name="parent_child_relations")
    op.drop_table("parent_child_relations")
    op.drop_index(op.f("ix_child_profiles_child_pseudonym_id"), table_name="child_profiles")
    op.drop_table("child_profiles")
    op.drop_index(op.f("ix_assessment_results_user_id"), table_name="assessment_results")
    op.drop_index(op.f("ix_assessment_results_subject"), table_name="assessment_results")
    op.drop_index(op.f("ix_assessment_results_pseudonym_id"), table_name="assessment_results")
    op.drop_index(op.f("ix_assessment_results_assessment_type"), table_name="assessment_results")
    op.drop_index("idx_result_user_type", table_name="assessment_results")
    op.drop_index("idx_result_subject_completed", table_name="assessment_results")
    op.drop_table("assessment_results")
    op.drop_index(op.f("ix_assessment_items_subject"), table_name="assessment_items")
    op.drop_index(op.f("ix_assessment_items_knowledge_point_id"), table_name="assessment_items")
    op.drop_index("idx_assessment_subject_grade", table_name="assessment_items")
    op.drop_index("idx_assessment_kp_difficulty", table_name="assessment_items")
    op.drop_table("assessment_items")
    # ### end Alembic commands ###
