"""
数据库模型包
精简版：仅保留核心业务模型
"""

from app.models.adaptive import (
    ExperimentAssignmentRecord,
    LearningTrajectoryRecord,
    OutcomeObservationRecord,
    PolicyBundleActivationRecord,
    PolicyBundleRecord,
    TeachingActionV03Record,
    TeachingContextRecord,
    TeachingEpisodeRecord,
)
from app.models.assessment import (
    AssessmentItem,
    AssessmentResult,
    CanonicalAssessmentAttemptRecord,
    CanonicalAssessmentResultRecord,
    LearnerEvidenceRecord,
    LearnerStateRecord,
    MasteryEstimateRecord,
)
from app.models.book_learning import BookLearningAdvanceRecord, BookLearningTranscriptTurnRecord
from app.models.consent import ConsentRecord, ConsentStatus, ConsentType
from app.models.data_control import (
    DataErasureCheckpointRecord,
    DataErasureReceiptRecord,
    DataErasureStepRecord,
    DataErasureWorkflowRecord,
)
from app.models.dialog import DialogMessage, DialogSession, MessageRole
from app.models.document import (
    DocumentChunk,
    DocumentCollectionAssignment,
    DocumentOcrCandidate,
    DocumentOcrRun,
    DocumentTagAssignment,
    DuplicateSuggestion,
    LibraryCollection,
    LibraryCommandReceipt,
    LibrarySearchProjection,
    LibraryTag,
    ModerationStatus,
    ProcessingStatus,
    UserDocument,
)
from app.models.goal_management import (
    FocusedGoalStateRecord,
    GoalAchievementEvaluationRecord,
    GoalAchievementPolicyRecord,
    GoalAssessmentActivityRecord,
    GoalChangePreviewRecord,
    GoalDefinitionRecord,
    GoalDraftRecord,
    GoalManagementCommandReceiptRecord,
    GoalObjectiveRecord,
    GoalPlanStateRecord,
    GoalStateRecord,
)
from app.models.identity import (
    AuthSessionRecord,
    IdentityCommandReceiptRecord,
    RecoveryCredentialRecord,
    RecoveryThrottleRecord,
)
from app.models.knowledge import KnowledgePoint, LearningMaterial
from app.models.ledger import (
    DecisionTraceInputRecord,
    DecisionTraceRecord,
    LearningEventRecord,
    OutboxTaskRecord,
    RecoveryEventRecord,
)
from app.models.onboarding import (
    OnboardingPreferenceCommandReceiptRecord,
    OnboardingPreferenceRecord,
)
from app.models.planning import (
    ActivityLifecycleCommandReceiptRecord,
    DiagnosticNeedRecord,
    GoalFormationInferenceRecord,
    GoalKnowledgeMappingRecord,
    GoalKnowledgeSubgraphRecord,
    LearningActivityRecord,
    LearningActivityStateRecord,
    LearningGoalRecord,
    LearningPlanRecord,
    ReviewObservationRecord,
    ReviewScheduleRecord,
)
from app.models.privacy import (
    AccountDeletionPreviewRecord,
    AccountDeletionRequestRecord,
    PrivacyTombstoneRecord,
)
from app.models.profile import UserProfile
from app.models.user import User, UserRole, UserStatus

__all__ = [
    "DataErasureCheckpointRecord",
    "DataErasureReceiptRecord",
    "DataErasureStepRecord",
    "DataErasureWorkflowRecord",
    "ConsentRecord",
    "ConsentStatus",
    "ConsentType",
    "ExperimentAssignmentRecord",
    "LearningTrajectoryRecord",
    "OutcomeObservationRecord",
    "PolicyBundleActivationRecord",
    "PolicyBundleRecord",
    "TeachingActionV03Record",
    "TeachingContextRecord",
    "TeachingEpisodeRecord",
    "User",
    "UserRole",
    "UserStatus",
    "AuthSessionRecord",
    "IdentityCommandReceiptRecord",
    "RecoveryCredentialRecord",
    "RecoveryThrottleRecord",
    "AccountDeletionPreviewRecord",
    "AccountDeletionRequestRecord",
    "PrivacyTombstoneRecord",
    "UserProfile",
    "DialogSession",
    "DialogMessage",
    "MessageRole",
    "KnowledgePoint",
    "LearningMaterial",
    "AssessmentItem",
    "AssessmentResult",
    "CanonicalAssessmentAttemptRecord",
    "CanonicalAssessmentResultRecord",
    "LearnerEvidenceRecord",
    "LearnerStateRecord",
    "MasteryEstimateRecord",
    "BookLearningTranscriptTurnRecord",
    "BookLearningAdvanceRecord",
    "ConsentRecord",
    "LearningActivityRecord",
    "LearningActivityStateRecord",
    "ActivityLifecycleCommandReceiptRecord",
    "DiagnosticNeedRecord",
    "LearningGoalRecord",
    "GoalKnowledgeMappingRecord",
    "GoalKnowledgeSubgraphRecord",
    "GoalFormationInferenceRecord",
    "LearningPlanRecord",
    "ReviewObservationRecord",
    "ReviewScheduleRecord",
    "GoalDefinitionRecord",
    "GoalStateRecord",
    "GoalPlanStateRecord",
    "GoalDraftRecord",
    "GoalChangePreviewRecord",
    "FocusedGoalStateRecord",
    "GoalManagementCommandReceiptRecord",
    "GoalAchievementPolicyRecord",
    "GoalObjectiveRecord",
    "GoalAssessmentActivityRecord",
    "GoalAchievementEvaluationRecord",
    "UserDocument",
    "DocumentChunk",
    "DocumentCollectionAssignment",
    "DocumentOcrCandidate",
    "DocumentOcrRun",
    "DocumentTagAssignment",
    "DuplicateSuggestion",
    "LibraryCollection",
    "LibraryCommandReceipt",
    "LibrarySearchProjection",
    "LibraryTag",
    "ProcessingStatus",
    "ModerationStatus",
    "LearningEventRecord",
    "DecisionTraceRecord",
    "DecisionTraceInputRecord",
    "OutboxTaskRecord",
    "RecoveryEventRecord",
    "OnboardingPreferenceRecord",
    "OnboardingPreferenceCommandReceiptRecord",
]
