"""
数据库模型包
精简版：仅保留核心业务模型
"""

from app.models.adaptive import (
    ExperimentAssignmentRecord,
    LearningTrajectoryRecord,
    OutcomeObservationRecord,
    PolicyBundleActivationRecord,
    PolicyBundleRecord,
    TeachingActionV03Record,
    TeachingContextRecord,
    TeachingEpisodeRecord,
)
from app.models.assessment import (
    AssessmentItem,
    AssessmentResult,
    CanonicalAssessmentAttemptRecord,
    CanonicalAssessmentResultRecord,
    LearnerEvidenceRecord,
    LearnerStateRecord,
    MasteryEstimateRecord,
)
from app.models.book_learning import BookLearningAdvanceRecord, BookLearningTranscriptTurnRecord
from app.models.dialog import DialogMessage, DialogSession, MessageRole
from app.models.document import (
    DocumentChunk,
    DocumentCollectionAssignment,
    DocumentOcrCandidate,
    DocumentOcrRun,
    DocumentTagAssignment,
    DuplicateSuggestion,
    LibraryCollection,
    LibraryCommandReceipt,
    LibrarySearchProjection,
    LibraryTag,
    ModerationStatus,
    ProcessingStatus,
    UserDocument,
)
from app.models.knowledge import KnowledgePoint, LearningMaterial
from app.models.ledger import (
    DecisionTraceInputRecord,
    DecisionTraceRecord,
    LearningEventRecord,
    OutboxTaskRecord,
    RecoveryEventRecord,
)
from app.models.planning import (
    ActivityLifecycleCommandReceiptRecord,
    DiagnosticNeedRecord,
    GoalFormationInferenceRecord,
    GoalKnowledgeMappingRecord,
    GoalKnowledgeSubgraphRecord,
    LearningActivityRecord,
    LearningActivityStateRecord,
    LearningGoalRecord,
    LearningPlanRecord,
    ReviewObservationRecord,
    ReviewScheduleRecord,
)
from app.models.profile import UserProfile
from app.models.user import User, UserRole, UserStatus

__all__ = [
    "ExperimentAssignmentRecord",
    "LearningTrajectoryRecord",
    "OutcomeObservationRecord",
    "PolicyBundleActivationRecord",
    "PolicyBundleRecord",
    "TeachingActionV03Record",
    "TeachingContextRecord",
    "TeachingEpisodeRecord",
    "User",
    "UserRole",
    "UserStatus",
    "UserProfile",
    "DialogSession",
    "DialogMessage",
    "MessageRole",
    "KnowledgePoint",
    "LearningMaterial",
    "AssessmentItem",
    "AssessmentResult",
    "CanonicalAssessmentAttemptRecord",
    "CanonicalAssessmentResultRecord",
    "LearnerEvidenceRecord",
    "LearnerStateRecord",
    "MasteryEstimateRecord",
    "BookLearningTranscriptTurnRecord",
    "BookLearningAdvanceRecord",
    "LearningActivityRecord",
    "LearningActivityStateRecord",
    "ActivityLifecycleCommandReceiptRecord",
    "DiagnosticNeedRecord",
    "LearningGoalRecord",
    "GoalKnowledgeMappingRecord",
    "GoalKnowledgeSubgraphRecord",
    "GoalFormationInferenceRecord",
    "LearningPlanRecord",
    "ReviewObservationRecord",
    "ReviewScheduleRecord",
    "UserDocument",
    "DocumentChunk",
    "DocumentCollectionAssignment",
    "DocumentOcrCandidate",
    "DocumentOcrRun",
    "DocumentTagAssignment",
    "DuplicateSuggestion",
    "LibraryCollection",
    "LibraryCommandReceipt",
    "LibrarySearchProjection",
    "LibraryTag",
    "ProcessingStatus",
    "ModerationStatus",
    "LearningEventRecord",
    "DecisionTraceRecord",
    "DecisionTraceInputRecord",
    "OutboxTaskRecord",
    "RecoveryEventRecord",
]
